<!DOCTYPE html>
 
<html>
<head>
   <meta http-equiv="content-type" content="text/html; charset=utf-8" />
   <title>Исключения в списке инициализации конструктора</title>
   <link href="/favicon.png" rel="icon" />
   <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-3017739-19']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

   <link rel="stylesheet" href="/css/screen.css" type="text/css" media="screen, projection" />
   <link rel="stylesheet" type="text/css" href="/css/highlight.css" />
   <link href="https://fonts.googleapis.com/css?family=PT+Serif:regular,italic,bold,bolditalic" rel="stylesheet" />
   <link href="https://fonts.googleapis.com/css?family=PT+Sans:regular,italic,bold,bolditalic" rel="stylesheet" /> 
   <link rel="alternate" title="Программирование - это просто!" href="/atom.xml" type="application/atom+xml">
</head>
<body>

<div class="site">

  <div class="menu">
    <a class="extra" href="/english">&laquo; english &raquo;</a>  
    <a href="/">блог</a> |
    <a href="/projects/">проекты</a> |
    <a href="/interview/">интервью</a> |
    <a href="/articles/">статьи</a> |
    <a href="/about/">автор</a>
  </div>

  <div id="home">
    <h1>Исключения в списке инициализации конструктора</h1>
<div id="post">
  <p>Правилом хорошего тона в С++ является использование списка инициализации для вызова конструкторов членов класса, например:</p>

<pre class="hl">
<span class="hl kwc">class</span> A <span class="hl opt">{ ... };</span>

<span class="hl kwc">class</span> B <span class="hl opt">{</span>
<span class="hl kwc">public</span><span class="hl opt">:</span>
  <span class="hl kwd">B</span><span class="hl opt">(</span><span class="hl kwb">int</span> n<span class="hl opt">);</span>
<span class="hl kwc">private</span><span class="hl opt">:</span>
  A __a<span class="hl opt">;</span>
<span class="hl opt">};</span>

B<span class="hl opt">::</span><span class="hl kwd">B</span><span class="hl opt">(</span><span class="hl kwb">int</span> n<span class="hl opt">)</span> 
  <span class="hl opt">:</span> <span class="hl kwd">__a</span><span class="hl opt">(</span>n<span class="hl opt">)</span>        <span class="hl slc">// вызов конструктора А() в списке инициализации.</span>
<span class="hl opt">{}</span>
</pre>

<p>А что произойдет, если в одном из вызовов в списке инициализации произойдет исключение? Например:</p>

<pre class="hl">
<span class="hl kwc">class</span> A <span class="hl opt">{</span>
<span class="hl kwc">public</span><span class="hl opt">:</span>
  <span class="hl kwd">A</span><span class="hl opt">(</span><span class="hl kwb">int</span> n<span class="hl opt">) {</span>
    <span class="hl kwa">throw</span> <span class="hl num">0</span><span class="hl opt">;</span>   <span class="hl slc">// Конструктор класса А бросает исключение int</span>
  <span class="hl opt">}</span>
<span class="hl opt">};</span>

<span class="hl kwc">class</span> B <span class="hl opt">{</span>
<span class="hl kwc">public</span><span class="hl opt">:</span>
  <span class="hl kwd">B</span><span class="hl opt">(</span><span class="hl kwb">int</span> n<span class="hl opt">);</span>
<span class="hl kwc">private</span><span class="hl opt">:</span>
  A __a<span class="hl opt">;</span>
<span class="hl opt">};</span>

B<span class="hl opt">::</span><span class="hl kwd">B</span><span class="hl opt">(</span><span class="hl kwb">int</span> n<span class="hl opt">)</span> 
  <span class="hl opt">:</span> <span class="hl kwd">__a</span><span class="hl opt">(</span>n<span class="hl opt">)</span>     <span class="hl slc">// Данный вызов бросает исключение</span>
<span class="hl opt">{}</span>
</pre>

<p>Хотелось бы иметь возможность поймать это исключение и провести &ldquo;чистку&rdquo; уже распределенной на тот момент памяти, например:</p>

<pre class="hl">
<span class="hl kwc">class</span> P <span class="hl opt">{ ... };</span>

<span class="hl kwc">class</span> A <span class="hl opt">{</span>
<span class="hl kwc">public</span><span class="hl opt">:</span>
  <span class="hl kwd">A</span><span class="hl opt">(</span><span class="hl kwb">int</span> n<span class="hl opt">) {</span>
    <span class="hl kwa">throw</span> <span class="hl num">0</span><span class="hl opt">;</span>   <span class="hl slc">// Конструктор класс А бросает исключение int</span>
  <span class="hl opt">}</span>
<span class="hl opt">};</span>

<span class="hl kwc">class</span> B <span class="hl opt">{</span>
<span class="hl kwc">public</span><span class="hl opt">:</span>
  <span class="hl kwd">B</span><span class="hl opt">();</span>
<span class="hl kwc">private</span><span class="hl opt">:</span>
  P<span class="hl opt">*</span> __p<span class="hl opt">;</span>
  A __a<span class="hl opt">;</span>
<span class="hl opt">};</span>

B<span class="hl opt">::</span><span class="hl kwd">B</span><span class="hl opt">()</span> 
  <span class="hl opt">:</span> <span class="hl kwd">__p</span><span class="hl opt">(</span><span class="hl kwa">new</span> P<span class="hl opt">),</span>    <span class="hl slc">// Память для P распределяется до вызова конструктора класса А</span>
  <span class="hl kwd">__a</span><span class="hl opt">(</span><span class="hl num">0</span><span class="hl opt">)</span>           <span class="hl slc">// Данный вызов бросает исключение</span>
<span class="hl opt">{}</span>
</pre>

<p>На момент, когда конструктор А бросит исключение, мы уже будем иметь распределенную память под указателем <code>__p</code> и, не обработав исключение, эту память можно потерять.</p>

<p>В С++ есть форма задания <code>try-catch</code> блока на уровне функции. Используя ее, можно переписать пример так:</p>

<pre class="hl">
<span class="hl ppc">#include &lt;iostream&gt;</span>

<span class="hl kwc">class</span> A <span class="hl opt">{</span>
<span class="hl kwc">public</span><span class="hl opt">:</span>
  <span class="hl kwd">A</span><span class="hl opt">(</span><span class="hl kwb">int</span> n<span class="hl opt">) {</span>
    <span class="hl kwa">throw</span> <span class="hl num">0</span><span class="hl opt">;</span>   <span class="hl slc">// Конструктор класс А бросает исключение int</span>
  <span class="hl opt">}</span>
<span class="hl opt">};</span>

<span class="hl kwc">class</span> P <span class="hl opt">{</span>
<span class="hl kwc">public</span><span class="hl opt">:</span>
  <span class="hl kwd">P</span><span class="hl opt">() {</span> std<span class="hl opt">::</span>cout <span class="hl opt">&lt;&lt;</span> <span class="hl str">&quot;P(), constructor&quot;</span> <span class="hl opt">&lt;&lt;</span> std<span class="hl opt">::</span>endl<span class="hl opt">; }</span>
  <span class="hl opt">~</span><span class="hl kwd">P</span><span class="hl opt">() {</span> std<span class="hl opt">::</span>cout <span class="hl opt">&lt;&lt;</span> <span class="hl str">&quot;~P(), destructor&quot;</span> <span class="hl opt">&lt;&lt;</span> std<span class="hl opt">::</span>endl<span class="hl opt">; }</span>
<span class="hl opt">};</span>

<span class="hl kwc">class</span> B <span class="hl opt">{</span>
<span class="hl kwc">public</span><span class="hl opt">:</span>
  <span class="hl kwd">B</span><span class="hl opt">();</span>
<span class="hl kwc">private</span><span class="hl opt">:</span>
  P<span class="hl opt">*</span> __p<span class="hl opt">;</span>
  A __a<span class="hl opt">;</span>
<span class="hl opt">};</span>

B<span class="hl opt">::</span><span class="hl kwd">B</span><span class="hl opt">()</span> 
<span class="hl kwa">try</span>
  <span class="hl opt">:</span> <span class="hl kwd">__p</span><span class="hl opt">(</span><span class="hl kwa">new</span> P<span class="hl opt">),</span> <span class="hl kwd">__a</span><span class="hl opt">(</span><span class="hl num">0</span><span class="hl opt">) {</span>
<span class="hl opt">}</span> <span class="hl kwa">catch</span> <span class="hl opt">(</span><span class="hl kwb">int</span><span class="hl opt">&amp;</span> e<span class="hl opt">) {</span>
  std<span class="hl opt">::</span>cout <span class="hl opt">&lt;&lt;</span> <span class="hl str">&quot;B(), exception &quot;</span> <span class="hl opt">&lt;&lt;</span> e <span class="hl opt">&lt;&lt;</span> std<span class="hl opt">::</span>endl<span class="hl opt">;</span>
  <span class="hl kwa">delete</span> __p<span class="hl opt">;</span>
<span class="hl opt">};</span>

<span class="hl kwb">int</span> <span class="hl kwd">main</span><span class="hl opt">(</span><span class="hl kwb">int</span> argc<span class="hl opt">,</span> <span class="hl kwb">char</span><span class="hl opt">*</span> argv<span class="hl opt">[]) {</span>
  <span class="hl kwa">try</span> <span class="hl opt">{</span>
    B b<span class="hl opt">;</span>
  <span class="hl opt">}</span> <span class="hl kwa">catch</span> <span class="hl opt">(</span><span class="hl kwb">int</span><span class="hl opt">&amp;</span> e<span class="hl opt">) {</span>
    std<span class="hl opt">::</span>cout <span class="hl opt">&lt;&lt;</span> <span class="hl str">&quot;main(), exception &quot;</span> <span class="hl opt">&lt;&lt;</span> e <span class="hl opt">&lt;&lt;</span> std<span class="hl opt">::</span>endl<span class="hl opt">;</span>
  <span class="hl opt">}</span>
<span class="hl opt">}</span>
</pre>

<p>Видно (см. тело конструктора <code>B::B()</code>), что лист инициализации ушел между словом <code>try</code> и началом try-блока, а тело конструктора теперь внутри try-блока (в данном примере оно пустое), а обработчик исключения находится в catch-блоке после тела конструктора. Данный пример сумеет обработать исключение класса А и освободит память из под указателя <code>__p</code>. Данный пример выведет следующее:</p>

<pre><code>P(), constructor
B(), exception 0
~P(), destructor
main(), exception 0
</code></pre>

<p>Видно, что деструктор класса <code>P</code> был вызван.</p>

<p>Внимательный читатель заметит, что в функции <code>main()</code> тоже есть try-блок, а последней строкой программа печатает <code>main(), exception 0</code>, что значит, что исключение было обработано дважды: в теле try-блока конструктора и затем в функции <code>main()</code>. Почему?</p>

<p>Правило гласит: исключение, пойманное в обрамляющем функцию виде <code>try-catch</code> блоке конструктора, будет переброшено еще раз при выходе из конструктора, если конструктор принудительно не сделал это сам, поймав это исключение. Сейчас очень важный момент: если хоть один из членов класса бросил исключение в процессе конструирования, то <strong>весь</strong> объект принудительно завершает конструирование аварийно с исключением вне зависимости от того, обработано это исключение в конструкторе или нет.</p>

<p>Единственное, что мы тут можем сделать, это &ldquo;на лету&rdquo; подправить исключение, брошенное членом класса (например, добавить туда дополнительную информацию). Следующий пример меняет код брошенного классом <code>А</code> исключения:</p>

<pre class="hl">
<span class="hl ppc">#include &lt;iostream&gt;</span>

<span class="hl kwc">class</span> A <span class="hl opt">{</span>
<span class="hl kwc">public</span><span class="hl opt">:</span>
  <span class="hl kwd">A</span><span class="hl opt">(</span><span class="hl kwb">int</span> n<span class="hl opt">) {</span>
    <span class="hl kwa">throw</span> <span class="hl num">0</span><span class="hl opt">;</span>   <span class="hl slc">// Конструктор класс А бросает исключение int</span>
  <span class="hl opt">}</span>
<span class="hl opt">};</span>

<span class="hl kwc">class</span> B <span class="hl opt">{</span>
<span class="hl kwc">public</span><span class="hl opt">:</span>
  <span class="hl kwd">B</span><span class="hl opt">();</span>
<span class="hl kwc">private</span><span class="hl opt">:</span>
  A __a<span class="hl opt">;</span>
<span class="hl opt">};</span>

B<span class="hl opt">::</span><span class="hl kwd">B</span><span class="hl opt">()</span> 
<span class="hl kwa">try</span>
  <span class="hl opt">:</span> <span class="hl kwd">__a</span><span class="hl opt">(</span><span class="hl num">0</span><span class="hl opt">) {</span>
<span class="hl opt">}</span> <span class="hl kwa">catch</span> <span class="hl opt">(</span><span class="hl kwb">int</span><span class="hl opt">&amp;</span> e<span class="hl opt">) {</span>
  std<span class="hl opt">::</span>cout <span class="hl opt">&lt;&lt;</span> <span class="hl str">&quot;B(), exception &quot;</span> <span class="hl opt">&lt;&lt;</span> e <span class="hl opt">&lt;&lt;</span> std<span class="hl opt">::</span>endl<span class="hl opt">;</span>
  e <span class="hl opt">=</span> <span class="hl num">1</span><span class="hl opt">;</span>      <span class="hl slc">// Меняем код исключения с 0 на 1.</span>
<span class="hl opt">};</span>

<span class="hl kwb">int</span> <span class="hl kwd">main</span><span class="hl opt">(</span><span class="hl kwb">int</span> argc<span class="hl opt">,</span> <span class="hl kwb">char</span><span class="hl opt">*</span> argv<span class="hl opt">[]) {</span>
  <span class="hl kwa">try</span> <span class="hl opt">{</span>
    B b<span class="hl opt">;</span>
  <span class="hl opt">}</span> <span class="hl kwa">catch</span> <span class="hl opt">(</span><span class="hl kwb">int</span><span class="hl opt">&amp;</span> e<span class="hl opt">) {</span>
    std<span class="hl opt">::</span>cout <span class="hl opt">&lt;&lt;</span> <span class="hl str">&quot;main(), exception &quot;</span> <span class="hl opt">&lt;&lt;</span> e <span class="hl opt">&lt;&lt;</span> std<span class="hl opt">::</span>endl<span class="hl opt">;</span>
  <span class="hl opt">}</span>
<span class="hl opt">}</span>
</pre>

<p>Эта программы выведет следующее:</p>

<pre><code>B(), exception 0
main(), exception 1
</code></pre>

<p>Видно, что когда исключение было поймано второй раз, код у него уже не 0 как в оригинальном исключении, а 1.</p>

<p>С конструкторами вроде разобрались. Перейдем к деструкторам.</p>

<p>Деструктор — это тоже функция. К нему тоже применим синтаксис ловли исключения на уровне тела функции, например:</p>

<pre class="hl">
<span class="hl ppc">#include &lt;iostream&gt;</span>

<span class="hl kwc">class</span> B <span class="hl opt">{</span>
<span class="hl kwc">public</span><span class="hl opt">:</span>
  <span class="hl opt">~</span><span class="hl kwd">B</span><span class="hl opt">();</span>
<span class="hl opt">};</span>

B<span class="hl opt">::~</span><span class="hl kwd">B</span><span class="hl opt">()</span> 
<span class="hl kwa">try</span> <span class="hl opt">{</span>
  <span class="hl kwa">throw</span> <span class="hl num">2</span><span class="hl opt">;</span>
<span class="hl opt">}</span> <span class="hl kwa">catch</span> <span class="hl opt">(</span><span class="hl kwb">int</span><span class="hl opt">&amp;</span> e<span class="hl opt">) {</span>
  std<span class="hl opt">::</span>cout <span class="hl opt">&lt;&lt;</span> <span class="hl str">&quot;~B(), exception &quot;</span> <span class="hl opt">&lt;&lt;</span> e <span class="hl opt">&lt;&lt;</span> std<span class="hl opt">::</span>endl<span class="hl opt">;</span>
<span class="hl opt">}</span>
</pre>

<p>Поведение ловли исключения в деструкторе на уровне функции схоже с конструктором, то есть исключение, пойманное в catch-блоке на уровне функции будет переброшено автоматически снова при завершении деструктора, если он это не сделал сам, обработав исключение. Например:</p>

<pre class="hl">
<span class="hl ppc">#include &lt;iostream&gt;</span>

<span class="hl kwc">class</span> B <span class="hl opt">{</span>
<span class="hl kwc">public</span><span class="hl opt">:</span>
  <span class="hl opt">~</span><span class="hl kwd">B</span><span class="hl opt">();</span>
<span class="hl opt">};</span>

B<span class="hl opt">::~</span><span class="hl kwd">B</span><span class="hl opt">()</span> 
<span class="hl kwa">try</span> <span class="hl opt">{</span>
  <span class="hl kwa">throw</span> <span class="hl num">2</span><span class="hl opt">;</span>
<span class="hl opt">}</span> <span class="hl kwa">catch</span> <span class="hl opt">(</span><span class="hl kwb">int</span><span class="hl opt">&amp;</span> e<span class="hl opt">) {</span>
  std<span class="hl opt">::</span>cout <span class="hl opt">&lt;&lt;</span> <span class="hl str">&quot;~B(), exception &quot;</span> <span class="hl opt">&lt;&lt;</span> e <span class="hl opt">&lt;&lt;</span> std<span class="hl opt">::</span>endl<span class="hl opt">;</span>
<span class="hl opt">}</span>

<span class="hl kwb">int</span> <span class="hl kwd">main</span><span class="hl opt">(</span><span class="hl kwb">int</span> argc<span class="hl opt">,</span> <span class="hl kwb">char</span><span class="hl opt">*</span> argv<span class="hl opt">[]) {</span>
  <span class="hl kwa">try</span> <span class="hl opt">{</span>
    B b<span class="hl opt">;</span>
  <span class="hl opt">}</span> <span class="hl kwa">catch</span> <span class="hl opt">(</span><span class="hl kwb">int</span><span class="hl opt">&amp;</span> e<span class="hl opt">) {</span>
    std<span class="hl opt">::</span>cout <span class="hl opt">&lt;&lt;</span> <span class="hl str">&quot;main(), B(), exception &quot;</span> <span class="hl opt">&lt;&lt;</span> e <span class="hl opt">&lt;&lt;</span> std<span class="hl opt">::</span>endl<span class="hl opt">;</span>
  <span class="hl opt">}</span>
<span class="hl opt">}</span>
</pre>

<p>выведет:</p>

<pre class="hl">
<span class="hl opt">~</span><span class="hl kwd">B</span><span class="hl opt">(),</span> exception <span class="hl num">2</span>
<span class="hl kwd">main</span><span class="hl opt">(),</span> <span class="hl kwd">B</span><span class="hl opt">(),</span> exception <span class="hl num">2</span>
</pre>

<p>то есть исключение, после его обработки в деструкторе было переброшено снова. Конечно, не пойманные исключения в деструкторе являются большим &ldquo;no-no!&rdquo; в С++. Принято считать, что не пойманное в деструкторе исключение — это прямой путь к аварийному завершению программы, так как нарушается принцип целостности системы исключений. Если хотите, чтобы ваши программы на С++ работали стабильно, то не допускайте, чтобы исключения “вылетали” из деструктора. Например так:</p>

<pre class="hl">
<span class="hl ppc">#include &lt;iostream&gt;</span>

<span class="hl kwc">class</span> B <span class="hl opt">{</span>
<span class="hl kwc">public</span><span class="hl opt">:</span>
  <span class="hl opt">~</span><span class="hl kwd">B</span><span class="hl opt">();</span>
<span class="hl opt">};</span>

B<span class="hl opt">::~</span><span class="hl kwd">B</span><span class="hl opt">() {</span>
  <span class="hl kwa">try</span> <span class="hl opt">{</span>
    <span class="hl kwa">throw</span> <span class="hl num">2</span><span class="hl opt">;</span>            <span class="hl slc">// Бросаем исключение.</span>
  <span class="hl opt">}</span> <span class="hl kwa">catch</span> <span class="hl opt">(</span><span class="hl kwb">int</span><span class="hl opt">&amp;</span> e<span class="hl opt">) {</span>    <span class="hl slc">// И тут же ловим его, не пропуская него “на волю”.</span>
    std<span class="hl opt">::</span>cout <span class="hl opt">&lt;&lt;</span> <span class="hl str">&quot;~B(), exception &quot;</span> <span class="hl opt">&lt;&lt;</span> e <span class="hl opt">&lt;&lt;</span> std<span class="hl opt">::</span>endl<span class="hl opt">;</span>
  <span class="hl opt">}</span>
<span class="hl opt">}</span>

<span class="hl kwb">int</span> <span class="hl kwd">main</span><span class="hl opt">(</span><span class="hl kwb">int</span> argc<span class="hl opt">,</span> <span class="hl kwb">char</span><span class="hl opt">*</span> argv<span class="hl opt">[]) {</span>
  <span class="hl kwa">try</span> <span class="hl opt">{</span>
    B b<span class="hl opt">;</span>
  <span class="hl opt">}</span> <span class="hl kwa">catch</span> <span class="hl opt">(</span><span class="hl kwb">int</span><span class="hl opt">&amp;</span> e<span class="hl opt">) {</span>
    std<span class="hl opt">::</span>cout <span class="hl opt">&lt;&lt;</span> <span class="hl str">&quot;main(), B(), exception &quot;</span> <span class="hl opt">&lt;&lt;</span> e <span class="hl opt">&lt;&lt;</span> std<span class="hl opt">::</span>endl<span class="hl opt">;</span>
  <span class="hl opt">}</span>
<span class="hl opt">}</span>
</pre>

<p>Эта программа выведет:</p>

<pre><code>~B(), exception 2
</code></pre>

<p>Видно, что исключение не дошло до функции <code>main()</code>.</p>

<p>С деструкторами тоже вроде разобрались. Теперь перейдем к обычным функциям.</p>

<p>Технику обработки исключений на уровне функции можно применять для любой функции, а не только для конструктора или деструктора, например:</p>

<pre class="hl">
<span class="hl kwb">void</span> <span class="hl kwd">f</span><span class="hl opt">()</span> 
<span class="hl kwa">try</span> <span class="hl opt">{</span>
  <span class="hl kwa">throw</span> <span class="hl num">1</span><span class="hl opt">;</span>
<span class="hl opt">}</span> <span class="hl kwa">catch</span> <span class="hl opt">(</span><span class="hl kwb">int</span><span class="hl opt">&amp;</span> e<span class="hl opt">) {</span>
  std<span class="hl opt">::</span>cout <span class="hl opt">&lt;&lt;</span> <span class="hl str">&quot;f(), exception &quot;</span> <span class="hl opt">&lt;&lt;</span> e <span class="hl opt">&lt;&lt;</span> std<span class="hl opt">::</span>endl<span class="hl opt">;</span>
<span class="hl opt">}</span>
</pre>

<p>Но целесообразность такого синтаксиса сомнительна, так как пойманное исключение <strong>не перебрасывается</strong> автоматически снова после окончания функции, как это было в случае с конструктором и деструктором. Программа:</p>

<pre class="hl">
<span class="hl ppc">#include &lt;iostream&gt;</span>

<span class="hl kwb">void</span> <span class="hl kwd">f</span><span class="hl opt">()</span> 
<span class="hl kwa">try</span> <span class="hl opt">{</span>
  <span class="hl kwa">throw</span> <span class="hl num">1</span><span class="hl opt">;</span>
<span class="hl opt">}</span> <span class="hl kwa">catch</span> <span class="hl opt">(</span><span class="hl kwb">int</span><span class="hl opt">&amp;</span> e<span class="hl opt">) {</span>
  std<span class="hl opt">::</span>cout <span class="hl opt">&lt;&lt;</span> <span class="hl str">&quot;f(), B(), exception &quot;</span> <span class="hl opt">&lt;&lt;</span> e <span class="hl opt">&lt;&lt;</span> std<span class="hl opt">::</span>endl<span class="hl opt">;</span>
<span class="hl opt">}</span>

<span class="hl kwb">int</span> <span class="hl kwd">main</span><span class="hl opt">(</span><span class="hl kwb">int</span> argc<span class="hl opt">,</span> <span class="hl kwb">char</span><span class="hl opt">*</span> argv<span class="hl opt">[]) {</span>
  <span class="hl kwa">try</span> <span class="hl opt">{</span>
    <span class="hl kwd">f</span><span class="hl opt">();</span>
  <span class="hl opt">}</span> <span class="hl kwa">catch</span> <span class="hl opt">(</span><span class="hl kwb">int</span><span class="hl opt">&amp;</span> e<span class="hl opt">) {</span>
    std<span class="hl opt">::</span>cout <span class="hl opt">&lt;&lt;</span> <span class="hl str">&quot;main(), f(), B(0), exception &quot;</span> <span class="hl opt">&lt;&lt;</span> e <span class="hl opt">&lt;&lt;</span> std<span class="hl opt">::</span>endl<span class="hl opt">;</span>
  <span class="hl opt">}</span>
<span class="hl opt">}</span>
</pre>

<p>напечатает только:</p>

<pre class="hl">
<span class="hl kwd">f</span><span class="hl opt">(),</span> <span class="hl kwd">B</span><span class="hl opt">(),</span> exception <span class="hl num">1</span>
</pre>

<p>то есть исключение не было передано дальше, поэтому разумнее было бы просто оформить функцию традиционным образом с помощью try-блока, обрамляющего всё тело функции:</p>

<pre class="hl">
<span class="hl kwb">void</span> <span class="hl kwd">f</span><span class="hl opt">() {</span>
  <span class="hl kwa">try</span> <span class="hl opt">{</span>
    <span class="hl kwa">throw</span> <span class="hl num">1</span><span class="hl opt">;</span>
  <span class="hl opt">}</span> <span class="hl kwa">catch</span> <span class="hl opt">(</span><span class="hl kwb">int</span><span class="hl opt">&amp;</span> e<span class="hl opt">) {</span>
    std<span class="hl opt">::</span>cout <span class="hl opt">&lt;&lt;</span> <span class="hl str">&quot;f(), B(), exception &quot;</span> <span class="hl opt">&lt;&lt;</span> e <span class="hl opt">&lt;&lt;</span> std<span class="hl opt">::</span>endl<span class="hl opt">;</span>
  <span class="hl opt">}</span>
<span class="hl opt">}</span>
</pre>

<p>не внося в форматирование текста лишней каши непривычным положением слов <code>try</code> и <code>catch</code>.</p>

<p>Лично мне кажется, из всего выше написанного, реально для применения только <code>try-catch</code> блок на уровне функции для конструктора. Там это действительно актуально, чтобы не допустить объектов, сконструированных только наполовину и убитых в процессе создания исключением от собственного члена (простите за каламбур).</p>

<p><strong>Выводы</strong></p>

<p>Исключения, брошенные при обработке списка инициализации класса можно поймать в теле конструктора через синтаксис <code>try-catch</code> блока на уровне функции.</p>

<p>Если хоть один элементов класса при конструировании выбросил исключение, то <strong>весь</strong> класс принудительно завершает собственное конструирование с ошибкой в форме исключения вне зависимости от того, было это исключение поймано в конструкторе или нет.</p>

</div>

<hr />


  <a href="http://easy-coding.blogspot.com/2009/02/blog-post_19.html"><small>Оригинальный пост</small></a> |


<a href="/about/"><small>Disclaimer</small></a>

<h1>Комментарии</h1>

<div id="disqus_thread"></div>

<script type="text/javascript">
  var disqus_shortname = 'easy-coding';
  var disqus_developer = 0;
  var disqus_identifier = 'http://easy-coding.blogspot.com/2009/02/blog-post_19.html';
  var disqus_url = 'http://easy-coding.blogspot.com/2009/02/blog-post_19.html';
  var disqus_script = 'embed.js';
  (function () {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = 'https://' + disqus_shortname + '.disqus.com/' + disqus_script;
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  }());
</script>


  </div>

  <div class="footer">
    <div class="contact">
      &copy; 2009-2013
      <a href="mailto:alexander@demin.ws">Александр Дëмин</a> |
      <a href="/atom.xml" rel="subscribe-rss" title="Подписаться через RSS">RSS</a>
    </div>
  </div>

</div>

</body>
</html>
